const projects = [
  {
    "id": "34",
    "name_id": "lepetitcamion",
    "name": "Le Petit Camion",
    "tags": "Le Petit Camion",
    "type": "website",
    "external_url": "http://lepetitcamion.com",
    "tools": "react js",
    "description": "project developed with <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2019-02-20"
  },
  {
    "id": "33",
    "name_id": "cloo",
    "name": "CLOO",
    "tags": "CLOO",
    "type": "website",
    "external_url": "http://cloo.pt",
    "tools": "html, css, js, php, mySLQ, custom cms",
    "description": "project developed with <a href=\"http://manoamanoclub.com\" target=\"_blank\">Mano a Mano</a>",
    "date": "2018-06-09"
  },
  {
    "id": "32",
    "name_id": "the-darjeeling-express",
    "name": "The Darjeeling Express",
    "tags": "The Darjeeling Express",
    "type": "website",
    "external_url": "http://thedarjeelingexpress.com",
    "tools": "html, stylus, js",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2018-03-01"
  },
  {
    "id": "31",
    "name_id": "ocolchete",
    "name": "o Colchete",
    "tags": "o Colchete",
    "type": "website",
    "external_url": "http://ocolchete.com",
    "tools": "html, css, js, php, mySLQ, custom cms",
    "description": "project developed with <a href=\"http://www.proto.pt\" target=\"_blank\">Proto</a>",
    "date": "2018-02-15"
  },
  {
    "id": "30",
    "name_id": "giao",
    "name": "Gião Drawings",
    "tags": "Gião Drawings",
    "type": "website",
    "external_url": "http://giao.pt",
    "tools": "html, css, js, php, mySLQ",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2018-01-15"
  },
  {
    "id": "29",
    "name_id": "tocarro",
    "name": "Tocarro",
    "tags": "Tocarro app",
    "type": "mobile app",
    "external_url": "https://itunes.apple.com/us/app/tocarro/id1334519301?ls=1&mt=8",
    "tools": "react-native",
    "description": "mobile app for real-time bus waiting times in Porto (STCP)",
    "date": "2018-01-14"
  },
  {
    "id": "28",
    "name_id": "joaobelo",
    "name": "João Belo",
    "tags": "João Belo",
    "type": "website",
    "external_url": "",
    "tools": "html, stylus, js, json api",
    "description": "version 5 of joaobelo.pt<br>check out how I made it <a target=\"_blank\" href=\"https://github.com/jpbelo/joaobelo-v5\">here</a>",
    "date": "2017-11-15"
  },
  {
    "id": "27",
    "name_id": "vimaplas",
    "name": "Vimaplás",
    "tags": "Vimaplás",
    "type": "website",
    "external_url": "http://vimaplas.pt",
    "tools": "html, css, js, jquery, php, custom cms",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2017-09-15"
  },
  {
    "id": "26",
    "name_id": "riopele",
    "name": "Riopele",
    "tags": "Riopele",
    "type": "website",
    "external_url": "https://riopele.pt",
    "tools": "html, css, js, jquery, php, custom cms",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2017-08-08"
  },
  {
    "id": "25",
    "name_id": "plataforma-do-mar",
    "name": "Plataforma do Mar",
    "tags": "plataforma do mar",
    "type": "website",
    "external_url": "http://plataformadomar.pt",
    "tools": "html, css, js, jquery, php, custom cms",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2017-05-07"
  },
  {
    "id": "24",
    "name_id": "cidades-de-excelencia",
    "name": "Cidades de Excelência",
    "tags": "cidades de excelência urbanismo acessibilidade",
    "type": "website",
    "external_url": "http://cidadesdeexcelencia.org",
    "tools": "html, css, js, jquery, php, custom cms",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2017-03-06"
  },
  {
    "id": "23",
    "name_id": "ess",
    "name": "ESS",
    "tags": "ESS engenharia",
    "type": "website",
    "external_url": "http://ess.pt",
    "tools": "html, css, js, jquery, php, custom cms",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2017-01-05"
  },
  {
    "id": "21",
    "name_id": "srnom",
    "name": "Secção Regional do Norte Ordem dos Médicos",
    "tags": "Secção Regional do Norte Ordem dos Médicos",
    "type": "website",
    "external_url": "http://nortemedico.pt",
    "tools": "angular2, html, css, js, jquery, php, custom cms",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2016-10-10"
  },
  {
    "id": "22",
    "name_id": "cesar-oliveira",
    "name": "César Oliveira fotografia",
    "tags": "César Oliveira, fotografia, portfolio",
    "type": "website",
    "external_url": "http://cesaroliveirafotografia.com",
    "tools": "html, css, js, jquery, php, custom cms",
    "description": "web design by Sergio Campos",
    "date": "2016-10-09"
  },
  {
    "id": "19",
    "name_id": "anabela-peres-de-sousa",
    "name": "Anabela Peres de Sousa",
    "tags": "Clínica dentária",
    "type": "website",
    "external_url": "http://anabelaperesdesousa.pt",
    "tools": "angular2, html, css, js",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2016-04-10"
  },
  {
    "id": "18",
    "name_id": "baby-gi",
    "name": "Baby Gi",
    "tags": null,
    "type": "website",
    "external_url": "http://babygi.pt",
    "tools": "html, css, jquery",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2016-03-07"
  },
  {
    "id": "17",
    "name_id": "327",
    "name": "327 Creative Studio",
    "tags": null,
    "type": "website",
    "external_url": "http://327.pt",
    "tools": "angular2, html, css, js, jquery, php, custom cms",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2015-11-18"
  },
  {
    "id": "16",
    "name_id": "combi-coffee",
    "name": "Combi Coffee",
    "tags": null,
    "type": "website",
    "external_url": "http://combicoffee.pt",
    "tools": "html, css, jquery",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2015-10-20"
  },
  {
    "id": "15",
    "name_id": "pratica04",
    "name": "Prática.04",
    "tags": null,
    "type": "website",
    "external_url": "http://pratica04.pt",
    "tools": "html, css, jquery",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2015-07-01"
  },
  {
    "id": "14",
    "name_id": "outlines",
    "name": "Outlines",
    "tags": null,
    "type": "website",
    "external_url": "http://outlines.pt",
    "tools": "html, css, jquery",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2015-03-27"
  },
  {
    "id": "4",
    "name_id": "boa-energia",
    "name": "Boa Energia",
    "tags": null,
    "type": "website",
    "external_url": "http://boaenergia.pt",
    "tools": "wordpress, woocomerce",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2015-03-11"
  },
  {
    "id": "11",
    "name_id": "aorp",
    "name": "AORP",
    "tags": "Associação de Ourivesaria e Relojoaria de Portugal",
    "type": "website",
    "external_url": "http://aorp.pt",
    "tools": "html, css, js, jquery, php, custom cms",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2014-12-20"
  },
  {
    "id": "10",
    "name_id": "oes",
    "name": "Ourivesaria em Segurança",
    "tags": null,
    "type": "website",
    "external_url": "http://ourivesariaemseguranca.pt",
    "tools": "html, css, js, jquery, php, custom cms",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2014-08-06"
  },
  {
    "id": "7",
    "name_id": "dreamdomus",
    "name": "Dreamdomus",
    "tags": "construção modular, domótica, segurança, climatização",
    "type": "website",
    "external_url": "http://dreamdomus.com",
    "tools": "html, css, js, jquery, php, custom cms",
    "description": "web design by Tiago Moutinho",
    "date": "2014-03-25"
  },
  {
    "id": "6",
    "name_id": "eio",
    "name": "EIO",
    "tags": "eio",
    "type": "website",
    "external_url": "http://eio.pt",
    "tools": "html, css, jquery",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2014-03-01"
  },
  {
    "id": "5",
    "name_id": "ppdc",
    "name": "PPDC",
    "tags": null,
    "type": "website",
    "external_url": "http://ppdcstudio.com",
    "tools": "html, css, js, jquery, php",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2013-12-01"
  },
  {
    "id": "13",
    "name_id": "outside-the-box",
    "name": "Outside the Box",
    "tags": null,
    "type": "website",
    "external_url": "http://outsidethebox.pt",
    "tools": "html, css, jquery",
    "description": "project developed at <a href=\"http://327.pt\" target=\"_blank\">327 creative studio</a>",
    "date": "2013-11-01"
  },
  {
    "id": "1",
    "name_id": "tiago-moutinho",
    "name": "Tiago Moutinho",
    "tags": "design, multimedia",
    "type": "website",
    "external_url": "http://tiagomoutinho.com",
    "tools": "html, css, jquery",
    "description": "web design by Tiago Moutinho",
    "date": "2013-01-01"
  }
];

export { projects }